export const products = [
	{
		id: 1,
		name: 'Product 1',
		price: 19.99,
		description: 'This is a great product.',
		imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-01.jpg',
		imageAlt: "Front of men's Basic Tee in black.",
		color: 'black',
		colors: [
			{ name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
			{ name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
			{ name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
		],
		sizes: [
			{ name: 'XXS', inStock: true },
			{ name: 'XS', inStock: true },
			{ name: 'S', inStock: true },
			{ name: 'M', inStock: true },
			{ name: 'L', inStock: true },
			{ name: 'XL', inStock: true },
			{ name: 'XXL', inStock: true },
			{ name: 'XXXL', inStock: false },
		],
		rating: 4,
		reviewCount: 34,
	},
	{
		id: 2,
		name: 'Product 2',
		price: 29.99,
		description: 'This is a great product.',
		imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-01.jpg',
		imageAlt: "Front of men's Basic Tee in black.",
		color: 'black',
		colors: [
			{ name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
			{ name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
			{ name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
		],
		sizes: [
			{ name: 'XXS', inStock: true },
			{ name: 'XS', inStock: true },
			{ name: 'S', inStock: true },
			{ name: 'M', inStock: true },
			{ name: 'L', inStock: true },
			{ name: 'XL', inStock: true },
			{ name: 'XXL', inStock: true },
			{ name: 'XXXL', inStock: false },
		],
		rating: 4,
		reviewCount: 34,
	},
	{
		id: 3,
		name: 'Product 3',
		price: 39.99,
		description: 'This is a great product.',
		imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-01.jpg',
		imageAlt: "Front of men's Basic Tee in black.",
		color: 'black',
		colors: [
			{ name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
			{ name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
			{ name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
		],

		sizes: [
			{ name: 'XXS', inStock: true },
			{ name: 'XS', inStock: true },
			{ name: 'S', inStock: true },
			{ name: 'M', inStock: true },
			{ name: 'L', inStock: true },
			{ name: 'XL', inStock: true },
			{ name: 'XXL', inStock: true },
			{ name: 'XXXL', inStock: false },
		],
		rating: 4,
		reviewCount: 34,
	},
	{
		id: 4,
		name: 'Product 4',
		price: 49.99,
		description: 'This is a great product.',
		imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-01.jpg',
		imageAlt: "Front of men's Basic Tee in black.",
		color: 'black',
		colors: [
			{ name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
			{ name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
			{ name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
		],
		sizes: [
			{ name: 'XXS', inStock: true },
			{ name: 'XS', inStock: true },
			{ name: 'S', inStock: true },
			{ name: 'M', inStock: true },
			{ name: 'L', inStock: true },
			{ name: 'XL', inStock: true },
			{ name: 'XXL', inStock: true },
			{ name: 'XXXL', inStock: false },
		],
		rating: 4,
		reviewCount: 34,
	},
];
